name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Installer les dépendances
        run: |
          pip install -r requirements.txt
          pip install pytest
      
      - name: Lancer les tests
        run: pytest test_devops_tool.py -v

  build:
    name: Build image Docker
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build de l'image
        run: docker build -t devops-tool:${{ github.sha }} .

      - name: Vérifie l'image
        run: docker run devops-tool:${{ github.sha }}
  
  push:
      name: Push sur Docker Hub
      runs-on: ubuntu-latest
      needs: build
      if: github.ref == 'refs/heads/main'

      steps:
        - name: Checkout du code
          uses: actions/checkout@v4

        - name: Login du Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB.TOKEN }}

        - name: Build et Push
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/devops-tool:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/devops-tool:${{ github.sha }}